### PR TITLE
Avoid generating exceptions for every terminal element

### LINKED ISSUE #918: QueuedSinglePublisher creates exception on every terminal item
While analyzing a new application's performance with Java Flight Recorder (during a load test), we noticed that there was a very high number of `CompletionException`(s) being generated. The stacktraces associated with these exceptions (which we never saw thrown) indicate they were created by `QueuedSinglePublisher` (we use reactive-feign, which uses jetty-reactive-httpclient).

It appears that the exceptions are being created 1:1 with requests, even successful requests!

Looking at the code of `QueuedSinglePublisher`, I noticed that a `CompletedException` is created when the "terminal" item in the reactive stream is encountered. If another attempt to process an element in the reactive stream occurs, it is then wrapped with an `IllegalStateException`, which is thrown.

Presumably, the idea here was to make it possible to see where the original terminal element was produced in the scenario where an "extra" element was produced after termination. This creates extra overhead for all HTTP requests, as each terminal operation requires the JRE to build out a stack trace.

### PR DESCRIPTION
**Pull request by chrisribble**
Fixes #918

### CODE REVIEW

File: src/main/java/org/eclipse/jetty/reactive/client/internal/QueuedSinglePublisher.java [hunk 1]
```diff
@@ -100,10 +100,10 @@ private boolean process(Object item) {
         Subscriber<? super T> subscriber;
         try (AutoLock ignored = lock()) {
             if (terminated != null) {
-                throw new IllegalStateException(terminated);
+                throw new IllegalStateException(new CompletionException("terminated from " + terminated, null));
             }
             if (isTerminal(item)) {
-                terminated = new CompletionException("terminated from " + Thread.currentThread(), null);
```
Comment (sbordet) [inline src/main/java/org/eclipse/jetty/reactive/client/internal/QueuedSinglePublisher.java:106]: The point of allocating the exception here was to capture the stack trace of the terminating thread.
Rethrowing as a nested exception of the ISE a couple of lines above loses that information, as it will capture the stack trace of the illegal call.

**Comment by sbordet** [comment]
@chrisribble what performance gain you get with your fix?

I ask because your fix removes a feature, so it needs to be evaluated.

**Comment by sbordet** [comment]
@chrisribble I'm inclined to use Jetty's `oej.util.ConstantThrowable` as a constant to be used as a sentinel, and if DEBUG enabled then use the old code.
Would that work for you?

Along the lines of:

```java
if (isTerminal(item)) {
    terminated = LOG.isDebugEnabled() 
        ? new CompletionException("terminated from " + Thread.currentThread(), null);
        : TERMINATED;
}
```
with

```java
private static final Throwable TERMINATED = new ConstantThrowable("terminated");
```

Thoughts?

File: src/main/java/org/eclipse/jetty/reactive/client/internal/QueuedSinglePublisher.java (hunk 1 above)
Comment (chrisribble) [reply src/main/java/org/eclipse/jetty/reactive/client/internal/QueuedSinglePublisher.java:106]: Yeah, I figured that was the intent behind capturing the exception in the terminating thread (to see the stacktrace where the initial termination happened).

**Comment by chrisribble** [comment]
> @chrisribble I'm inclined to use Jetty's `oej.util.ConstantThrowable` as a constant to be used as a sentinel, and if DEBUG enabled then use the old code.
> Would that work for you?
> 
> Along the lines of:
> 
> ```java
> if (isTerminal(item)) {
>     terminated = LOG.isDebugEnabled() 
>         ? new CompletionException("terminated from " + Thread.currentThread(), null);
>         : TERMINATED;
> }
> ```
> with
> 
> ```java
> private static final Throwable TERMINATED = new ConstantThrowable("terminated");
> ```
> 
> Thoughts?

It would solve the problem I am trying to solve. 

However, I think it may violate the principle of least astonishment by changing the stacktrace based on the log level. If I was trying to understand an actual exception that was thrown and then turned up the log level to debug, I would be very confused to see a different exception/stacktrace in play.

Perhaps it would be better to have a system property that enables capturing the stacktrace this way?

**Comment by sbordet** [comment]
> If I was trying to understand an actual exception that was thrown and then turned up the log level to debug, I would be very confused to see a different exception/stacktrace in play.

Without DEBUG logging enabled, you would not see any additional stack trace, as `ConstantThrowable` does not have a stack trace at all.
You would only see the `IllegalStateException` stack trace.

> Perhaps it would be better to have a system property that enables capturing the stacktrace this way?

By the same account, it would also break the principle.

I think it's acceptable to turn on DEBUG level and see more information, and pay more cost, and if there is a problem, the DEBUG logs would show it clearly.

I don't think there will be confusion, as in the non-DEBUG case there is no stack trace.

If you agree with this solution and want to make the changes in this PR (and possibly test them), I'd be happy to review them.

**Comment by chrisribble** [comment]
I ran my application with these changes and everything looks good. I also collected a new JFR and I no longer see thousands of `CompletionException`(s) created by jetty-reactive-httpclient (in fact, there are zero).

It's hard to make an apples-to-apples CPU usage comparison, but according to the JFR's that I collected, the time spent in `java.lang.Throwable.fillInStackTrace(int)` dropped from 0.117% to 0.069% (of course, there are still various other exceptions in my application, primarily triggered by HTTP requests failing for transient status code, etc).

**Review by sbordet — APPROVED** [review]

**Comment by sbordet** [comment]
@chrisribble merged, thanks!
